In [1]:

import pandas_datareader as web
import pandas as pd
start = pd.to_datetime('2012-01-01')
end = pd.to_datetime('today')

df_web_aapl = web.DataReader('AAPL', data_source='yahoo', start=start, end=end)[:2156]
df_web_aapl.columns = ['High_AAPL', 'Low_AAPL', 'Open_AAPL', 'Close_AAPL', 'Volume_AAPL', 'Adj_Close_AAPL']
df_web_fb = web.DataReader('FB', data_source='yahoo', start=start, end=end)[:2156]
df_web_fb.columns = ['High_FB', 'Low_FB', 'Open_FB', 'Close_FB', 'Volume_FB', 'Adj_Close_FB']
df_web_amzn = web.DataReader('AMZN', data_source='yahoo', start=start, end=end)[:2156]
df_web_amzn.columns = ['High_AMZN', 'Low_AMZN', 'Open_AMZN', 'Close_AMZN', 'Volume_AMZN', 'Adj_Close_AMZN']
df_web_googl = web.DataReader('GOOGL', data_source='yahoo', start=start, end=end)[:2156]
df_web_googl.columns = ['High_GOOGL', 'Low_GOOGL', 'Open_GOOGL', 'Close_GOOGL', 'Volume_GOOGL', 'Adj_Close_GOOGL']
df_web_vix = web.DataReader('^VIX', data_source='yahoo', start=start, end=end)[:2156]
df_web_vix.columns = ['High_VIX', 'Low_VIX', 'Open_VIX', 'Close_VIX', 'Volume_VIX', 'Adj_Close_VIX']
df_web_vix = df_web_vix[['High_VIX', 'Low_VIX', 'Open_VIX', 'Close_VIX']]
df_web_samsung = web.DataReader('005930.KS', 'yahoo', start , end)[:2156]
df_web_samsung.columns= ['High_SAMSUNG', 'Low_SAMSUNG', 'Open_SAMSUNG', 'Close_SAMSUNG', 'Volume_SAMSUNG', 'Adj_Close_SAMSUNG']

list_stocks = ["SAMSUNG", "AAPL", "AMZN", "GOOGL"]

df_gafa_and_vix =pd.concat([df_web_aapl,df_web_amzn,df_web_googl,df_web_samsung,df_web_vix], axis=1)  # je mets pas celui de fb psq ca marche pas

df_gafa_and_vix = df_gafa_and_vix[1:-220]
df_gafa_and_vix.head()

,High_AAPL,Low_AAPL,Open_AAPL,Close_AAPL,Volume_AAPL,Adj_Close_AAPL,High_AMZN,Low_AMZN,Open_AMZN,Close_AMZN,...,High_SAMSUNG,Low_SAMSUNG,Open_SAMSUNG,Close_SAMSUNG,Volume_SAMSUNG,Adj_Close_SAMSUNG,High_VIX,Low_VIX,Open_VIX,Close_VIX
Date,,,,,,,,,,,,,,,,,,,,,
2012-01-03,14.732142,14.607142,14.621428,14.686786,302220800.0,12.566676,179.479996,175.550003,175.889999,179.029999,...,22100.0,21840.0,21860.0,22100.0,16927750.0,21.363358,23.100000,22.540001,22.950001,22.969999
2012-01-04,14.810000,14.617143,14.642858,14.765715,260022000.0,12.634213,180.500000,176.070007,179.210007,177.509995,...,22200.0,21500.0,22100.0,21600.0,17103700.0,20.880024,23.730000,22.219999,23.440001,22.219999
2012-01-05,14.948215,14.738214,14.819643,14.929643,271269600.0,12.774481,178.250000,174.050003,175.940002,177.610001,...,21580.0,21100.0,21460.0,21100.0,17298400.0,20.396688,23.090000,21.340000,22.750000,21.480000
2012-01-06,15.098214,14.972143,14.991786,15.085714,318292800.0,12.908023,184.649994,177.500000,178.070007,182.610001,...,21320.0,20600.0,21120.0,20800.0,18816250.0,20.106688,21.719999,20.580000,21.240000,20.629999
2012-01-09,15.276786,15.048214,15.196428,15.061786,394024400.0,12.887549,184.369995,177.000000,182.759995,178.559998,...,20820.0,20300.0,20800.0,20320.0,19283000.0,19.642691,21.780001,21.000000,21.670000,21.070000

In [2]:
df_web_samsung.isnull().sum()

High_SAMSUNG         0
Low_SAMSUNG          0
Open_SAMSUNG         0
Close_SAMSUNG        0
Volume_SAMSUNG       0
Adj_Close_SAMSUNG    0
dtype: int64

In [3]:
df_gafa_and_vix.isnull().sum()

High_AAPL             58
Low_AAPL              58
Open_AAPL             58
Close_AAPL            58
Volume_AAPL           58
Adj_Close_AAPL        58
High_AMZN             58
Low_AMZN              58
Open_AMZN             58
Close_AMZN            58
Volume_AMZN           58
Adj_Close_AMZN        58
High_GOOGL            58
Low_GOOGL             58
Open_GOOGL            58
Close_GOOGL           58
Volume_GOOGL          58
Adj_Close_GOOGL       58
High_SAMSUNG         109
Low_SAMSUNG          109
Open_SAMSUNG         109
Close_SAMSUNG        109
Volume_SAMSUNG       109
Adj_Close_SAMSUNG    109
High_VIX              58
Low_VIX               58
Open_VIX              58
Close_VIX             58
dtype: int64